declare module "AXIOS/axios";
declare module "OPMS/routes";
declare module "MDM/routes";
declare module "EDXPERT/routes";
declare module "UI/button";
declare module "UI/table";
declare module 'UI/contentSkeleton'
declare module 'UI/input'
declare module 'UI/utils'
declare module 'UI/select'
